# 1. Build 단계
FROM node:20-alpine AS builder
WORKDIR /app

COPY .env .env


COPY app/package*.json ./
RUN npm ci
COPY app/ .

RUN npm run build   # Next.js 빌드

# 2. Run 단계
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000

COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/.next ./.next

EXPOSE 3000
CMD ["npm", "start"]   
# Next.js 프로덕션 서버 실행